language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master
  keep_history: true
  repo: JeffResc/jeffresc.github.io
  fqdn: jeffresc.dev
  committer_from_gh: true
  on:
    branch: master
